### PR TITLE
Improve Visual Studio support.

### PR DESCRIPTION
**Pull request by haydenroche5**
This commit moves all the Windows Visual Studio files into the windows/
subdirectory. windows/ contains separate subdirectories and solutions for FIPS
140-2 and non-FIPS cases. I've also updated the documentation.

Depends on https://github.com/wolfSSL/wolfssl/pull/4840.

### CODE REVIEW

**Comment by julek-wolfssl** [comment]
Initial pass through looks good. Is there a reason to make separate solutions instead of having a single solution and add configurations on top?

**Comment by haydenroche5** [comment]
> Initial pass through looks good. Is there a reason to make separate solutions instead of having a single solution and add configurations on top?

No particular reason. That actually sounds better. I'll look into it.

**Comment by julek-wolfssl** [comment]
It would be great to have the base configurations and then have the FIPS solutions build on top of that. That way changes will need to be made only to the base configurations.

**Comment by haydenroche5** [comment]
> It would be great to have the base configurations and then have the FIPS solutions build on top of that. That way changes will need to be made only to the base configurations.

Yeah, I agree. Will look into it.

**Review by julek-wolfssl — CHANGES_REQUESTED** [review]
Great work on improving Windows VS solution support!

1. As we discussed already. Please try to re-use configurations where possible. You found that you could use property sheets to that end which I think is great. Maintaining 12 distinct configurations (actually 24 due to x86 and x64 platforms) is not feasible in the long run.
https://docs.microsoft.com/en-us/cpp/build/create-reusable-property-configurations?view=msvc-170
2. I think you didn't clean up the test project files in the `test` directory.
3. In the `*.vcxproj` files you specified `v142` as the `PlatformToolset`. This corresponds to Visual Studio 2019. While I also would like to go back to 2019, it appears that VS 2022 has been released and I think its good practice to set the defaults to the latest version. This will avoid reports of customers trying to compile the solution with a `PlatformToolset` that they don't have installed.
`PlatformToolset` list: https://docs.microsoft.com/en-us/cpp/build/how-to-modify-the-target-framework-and-platform-toolset?view=msvc-170

**Comment by haydenroche5** [comment]
@julek-wolfssl I believe I've addressed all your feedback, but let me know if I missed anything / if you have any new comments.

**Review by julek-wolfssl — CHANGES_REQUESTED** [review]
@haydenroche5 These changes are absolutely great! Amazing work! The only thing missing is you somehow deleted `windows/README.md`. Please restore it and add a `# Development` section with a note about the property sheets (i.e. that all config needs to go the lowest possible property sheet and the properties of specific configs should not be modified past what is already in them).

**Comment by haydenroche5** [comment]
> @haydenroche5 These changes are absolutely great! Amazing work!

Thanks!

> The only thing missing is you somehow deleted `windows/README.md`. Please restore it and add a `# Development` section with a note about the property sheets (i.e. that all config needs to go the lowest possible property sheet and the properties of specific configs should not be modified past what is already in them).

Thanks for the catch. Added it back and added a development section.

**Review by julek-wolfssl — APPROVED** [review]
Great! I'm really liking the use of property sheets. We need to get this in wolfSSL ASAP. Over to @cconlon for a final review.

**Review by cconlon — APPROVED** [review]

**Pull request merged**
